
- name: Ensure PostgreSQL is started on boot
  service: name=postgresql-{{ postgresql_version }} enabled=yes

- name: Configure PostgreSQL database connection for XWiki
  template:
    src: templates/hibernate.cfg.xml.j2
    dest: "{{ xwiki_path }}/webapps/ROOT/WEB-INF/hibernate.cfg.xml"
    owner: "{{ xwiki_user }}"
    group: "{{ xwiki_group }}"
    mode: 0600
  notify: service restart tomcat

- name: Ensure libsemanage-python is installed
  yum: name=libsemanage-python state=present
  when: ansible_os_family == "RedHat"

- name: Ensure libsemanage-python is installed
  apt: name=libsemanage-python state=present
  when: ansible_os_family == "Debian"

- name: Set (httpd_can_network_connect) flag on and keep it persistent across reboots
  seboolean: name=httpd_can_network_connect state=yes persistent=yes
  when: ansible_selinux.status == "enabled"
