
- name: Ensure PostgreSQL is started on boot
  service: name=postgresql-{{ postgresql_version }} enabled=yes

- name: Configure PostgreSQL database connection for XWiki
  template:
    src: templates/hibernate.cfg.xml.j2
    dest: "{{ xwiki_path }}/webapps/ROOT/WEB-INF/hibernate.cfg.xml"
    owner: "{{ xwiki_user }}"
    group: "{{ xwiki_group }}"
    mode: 0600
  notify: Restart tomcat-xwiki

- name: Generate random xwiki.authentication.validationKey
  command: openssl rand -base64 32
  register: validationKey

- name: Generate random xwiki.authentication.encryptionKey
  command: openssl rand -base64 32
  register: encryptionKey

- name: Configure Xwiki (properties file)
  template:
    src: templates/xwiki.properties.j2
    dest: "{{ xwiki_path }}/webapps/ROOT/WEB-INF/xwiki.properties"
    owner: "{{ xwiki_user }}"
    group: "{{ xwiki_group }}"
    mode: 0600
  notify: Restart tomcat-xwiki

- name: Configure Xwiki (cfg file)
  template:
    src: templates/xwiki.cfg.j2
    dest: "{{ xwiki_path }}/webapps/ROOT/WEB-INF/xwiki.cfg"
    owner: "{{ xwiki_user }}"
    group: "{{ xwiki_group }}"
    mode: 0600
  notify: Restart tomcat-xwiki

- name: Ensure libsemanage-python is installed
  yum: name=libsemanage-python state=present
  when: ansible_os_family == "RedHat" and ansible_selinux.status == "enabled"

- name: Ensure libsemanage-python is installed
  apt: name=libsemanage-python state=present
  when: ansible_os_family == "Debian" and ansible_selinux.status == "enabled"

- name: Set (httpd_can_network_connect) flag on and keep it persistent across reboots
  seboolean: name=httpd_can_network_connect state=yes persistent=yes
  when: ansible_selinux.status == "enabled"
