---

- hosts: all
  remote_user: root
  become: yes

  vars_files:
    - ./defaults.yml
    - ./vars.yml

  tasks:
    - include: ./install_xwiki.yml
    - include: ./configure_xwiki.yml

  roles:
    # Database installation and configuration
    # JDBC Driver https://jdbc.postgresql.org/download/postgresql-9.4.1207.jar
    - role: ANXS.postgresql
      postgresql_version: "{{xwiki_postgresql_version}}"
      postgresql_encoding: "{{xwiki_postgresql_encoding}}"

      postgresql_databases:
        - name: "{{xwiki_database}}"
          owner: "{{xwiki_database_user}}"

      postgresql_users:
        - name: "{{xwiki_database_user}}"
          pass: "{{xwiki_database_user_pass}}"

      postgresql_user_privileges:
        - name: "{{xwiki_database_user}}"
          db: "{{xwiki_database}}"

    - role: silpion.java
      oracle_java_distribution: srv
      oracle_java_version: "{{ xwiki_java_version }}"

    - role: groover.tomcat
      tomcat_version: "{{ xwiki_tomcat_version }}"
      tomcat_instances:
      - name: xwiki
        user: "{{ xwiki_user }}"
        group: "{{ xwiki_group }}"
        path: "{{ xwiki_tomcat_path }}"
        home: /home/{{ xwiki_user }}
        service_name: tomcat-xwiki
        service_file: tomcat-xwiki.service
        port_ajp: 18009
        port_connector: 18080
        port_redirect: 18443
        port_shutdown: 18005
