---

- hosts: all
  remote_user: root
  become: yes

  vars_files:
    - ./defaults.yml
    - ./vars.yml

  roles:
    # Database installation and configuration
    - role: ANXS.postgresql
      postgresql_version: "{{xwiki_postgresql_version}}"
      postgresql_encoding: "{{xwiki_postgresql_encoding}}"

      postgresql_databases:
        - name: "{{xwiki_database}}"
          owner: "{{xwiki_database_user}}"

      postgresql_users:
        - name: "{{xwiki_database_user}}"
          pass: "{{xwiki_database_user_pass}}"

      postgresql_user_privileges:
        - name: "{{xwiki_database_user}}"
          db: "{{xwiki_database}}"

    # # Java installation and configuration
    # - role: ansiblebit.oracle-java
    #   oracle_java_version: "{{xwiki_java_version}}"
    #   oracle_java_set_as_default: yes

    # - role: tomcat
    #   tomcat_version: "8.0.32"
    #   tomcat_install_base: /usr/local

    - role: silpion.java

    - role: groover.tomcat
      tomcat_instances:
      - name: xwiki
        user: xwiki
        group: xwiki
        path: /srv/xwiki
        home: /home/xwiki
        service_name: xwiki@tomcat
        service_file: xwiki@.service
        port_ajp: 18009
        port_connector: 18080
        port_redirect: 18443
        port_shutdown: 18005
