---
- hosts: all
  remote_user: root
  become: yes

  vars_files:
    - ./defaults.yml
    - ./vars.yml
    - ./secrets.yml

  pre_tasks:
    - name: Ensure "apache" user exists
      yum: name=httpd state=present

    - name: Ensure "postfix" user exists
      yum: name=postfix state=present

  roles:
    # Database installation and configuration
    - role: ANXS.postgresql
      postgresql_version: "{{xwiki_postgresql_version}}"
      postgresql_encoding: "{{xwiki_postgresql_encoding}}"

      postgresql_databases:
        - name: "{{xwiki_database}}"
          owner: "{{xwiki_database_user}}"

      postgresql_users:
        - name: "{{xwiki_database_user}}"
          pass: "{{xwiki_database_user_pass}}"

      postgresql_user_privileges:
        - name: "{{xwiki_database_user}}"
          db: "{{xwiki_database}}"

    - role: silpion.java
      oracle_java_distribution: srv
      oracle_java_version: "{{ xwiki_java_version }}"

    - role: groover.tomcat
      tomcat_version: "{{ xwiki_tomcat_version }}"
      tomcat_instances:
      - name: xwiki
        user: "{{ xwiki_user }}"
        group: "{{ xwiki_group }}"
        path: "{{ xwiki_tomcat_path }}"
        home: /home/{{ xwiki_user }}
        service_name: tomcat-xwiki
        service_file: tomcat-xwiki.service
        catalina_opts: "{{ xwiki_catalina_opts}}"
        port_ajp: 18009
        port_connector: 18080
        port_redirect: 18443
        port_shutdown: 18005

    # SSL certificate for the web server
    - role: jdauphant.ssl-certs
      ssl_certs_common_name: "{{ servername }}"
      ssl_certs_path_owner: "apache"
      ssl_certs_path_group: "apache"
      ssl_certs_country: "EU"
      ssl_certs_locality: "Europe"
      ssl_certs_organization: "climateurope"
      ssl_certs_state: "Europe"
      ssl_certs_days: "1825"

    - role: geerlingguy.apache
      apache_global_vhost_settings: |
        SSLProxyEngine on
      apache_vhosts:
        - servername: "{{ servername }}"
          documentroot: "/var/www/html"
          extra_parameters: |
            Redirect / https://{{ servername }}/
      apache_vhosts_ssl:
        - servername: "{{ servername }}"
          documentroot: "/var/www/html"
          certificate_file: "/etc/ssl/{{servername}}/{{servername}}.pem"
          certificate_key_file: "/etc/ssl/{{servername}}/{{servername}}.key"
          certificate_chain_file: "/etc/ssl/{{servername}}/{{servername}}.csr"
          extra_parameters: |
            ProxyRequests   Off
            ProxyPreserveHost On
            ProxyPass / ajp://localhost:18009/
            ProxyPassReverse / ajp://localhost:18009/

    - role: rastandy.postfix
      postfix_hostname: "{{ servername }}"

    - role: geerlingguy.firewall
      firewall_allowed_tcp_ports:
        - "22"
        - "80"
        - "443"

  tasks:
    - include: ./install.yml
    - include: ./configure.yml

  handlers:
    - name: Restart tomcat-xwiki
      service:
        name: tomcat-xwiki
        state: restarted
