---

- src: https://github.com/ANXS/postgresql
  name: ANXS.postgresql
  version: 04d90828102926f5c7094bb1c8aa907d9a5335d2

- src: https://github.com/rastandy/ansible-tomcat
  name: groover.tomcat
  version: 72a7fd4a5f68bed05503abe3e33361c051419c66

- src: https://github.com/rastandy/ansible-java
  name: silpion.java
  version: ee5e9582dad0a517839fd0d6f4852fe6d018271b

- src: https://github.com/rastandy/ansible-role-apache
  name: rastandy.apache

- src: https://github.com/rastandy/ansible-role-ssl-certs
  name: jdauphant.ssl-certs

- src: https://github.com/geerlingguy/ansible-role-firewall
  name: geerlingguy.firewall

- src: https://github.com/rastandy/postfix
  name: rastandy.postfix

- src: https://github.com/rastandy/Stouts.backup
  name: Stouts.backup

- src: bennojoy.ntp

- src: https://github.com/rastandy/ansible-role-bacula-client
  name: rastandy.bacula-client

- src: https://github.com/rastandy/riemann-server-ansible-role
  name: rastandy.riemann-server

- src: https://github.com/rastandy/riemann-client-ansible-role
  name: rastandy.riemann-client

- src: https://github.com/rastandy/ansible-collectd
  name: rastandy.collectd

- src: https://github.com/rastandy/libreoffice-server-ansible-role
  name: rastandy.libreoffice-server
